version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studentpm-frontend
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    networks:
      - studentpm-network
    restart: unless-stopped
    # depends_on:
    #   - student-pm-api-gateway

# Используется внешняя сеть, созданная бэкендом, чтобы
# фронт мог обращаться по имени к api-gateway.
# Создать: docker network create studentpm-network
networks:
  studentpm-network:
    # external: true
    driver: bridge
